[build]
  publish = "dist"
  command = "echo 'Skipping remote build - using local dist' && ls -la"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://web-production-f9c83.up.railway.app/api"