name: cleaning-app
services:
- name: backend
  source_dir: /backend
  github:
    repo: votre-username/cleaning-app
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    type: SECRET
  - key: JWT_SECRET
    type: SECRET

- name: frontend
  source_dir: /frontend
  github:
    repo: votre-username/cleaning-app
    branch: main
    deploy_on_push: true
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: VITE_API_URL
    value: ${backend.PUBLIC_URL}/api

databases:
- engine: PG
  name: cleaning-db
  num_nodes: 1
  size: db-s-dev-database
  version: "14"

domain:
  minimum_tls_version: "1.2"