name: Security Scan

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    name: Security Audit
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Audit backend dependencies
        working-directory: ./backend
        run: |
          npm ci
          npm audit --audit-level high

      - name: Audit frontend dependencies
        working-directory: ./frontend
        run: |
          npm ci
          npm audit --audit-level high

  container-scan:
    runs-on: ubuntu-latest
    name: Container Security Scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t backend-scan ./backend

      - name: Build frontend image
        run: docker build -t frontend-scan ./frontend

      - name: Scan backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend-scan'
          format: 'sarif'
          output: 'backend-scan.sarif'

      - name: Scan frontend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend-scan'
          format: 'sarif'
          output: 'frontend-scan.sarif'

      - name: Upload backend scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'backend-scan.sarif'

      - name: Upload frontend scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'frontend-scan.sarif'